resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
packages:
- '.'
- location:
    git: git@github.com:reflex-frp/reflex.git
    commit: d78ba4318c425ca9b942dc387d7c5c7ab2d2e095
- location:
    git: git@github.com:reflex-frp/reflex-dom.git
    commit: ff9351a1859a07f8f3892d6381e9d5d0cd500d5d

extra-deps:
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
- data-default-0.6.0
- data-default-instances-base-0.1.0.1
- prim-uniq-0.1.0.1
- zenc-0.1.1
